apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-page-generator
  namespace: jams
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: static-page-generator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: static-page-generator
    spec:
      containers:
        - name: static-page-generator-container
          image: bnova/static-page-generator:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: static-page-generator
  namespace: jams
spec:
  type: LoadBalancer
  selector:
    app: static-page-generator
  ports:
    - name: http
      port: 3000
      targetPort: http
