---
source_git_repository_url: "https://github.com/b-nova-openhub"
source_git_repository_branch: "main"
source_git_repository_username: ""
source_git_repository_password: ""
target_git_repository_absolute_path: "/Users/rschneider/tmp/"
target_git_repository_relative_path: "content/"
content_permalink_base: "b-nova.com"
content_frontmatter_open: "<b-nova-content-header>"
content_frontmatter_close: "</b-nova-content-header>"